esphome:
  name: mintymcu_panel
  platform: ESP8266
  board: d1_mini_lite

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: True
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

i2c:
  sda: D1
  scl: D2

switch:
  # System
  - platform: restart
    name: "MintyMCU_Control_Panel Restart"
  - platform: gpio
    pin: D3
    id: switch_panel_led
  - platform: template
    name: "MintyMCU_Control_Panel LED"
    turn_on_action:
      - switch.turn_on: switch_panel_led
      - delay: 500ms
      - switch.turn_off: switch_panel_led

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x32"
    # reset_pin: D0
    address: 0x3C
    lambda: |-
      it.print("Hello World!");

sensor:
  - platform: wifi_signal
    name: "MintyMCU_Control_Panel WiFi Signal Sensor"
    update_interval: 60s
  - platform: uptime
    name: "MintyMCU_Control_Panel Uptime Sensor"
    update_interval: 60s
    filters:
      - lambda: return x / (24 * 3600);
    unit_of_measurement: "days"
  - platform: rotary_encoder
    name: "MintyMCU_Control_Panel Rotary Encoder"
    pin_a: D5
    pin_b: D6
    resolution: 1
    min_value: 0
    max_value: 60
  - platform: adc
    pin: A0
    name: "MintyMCU_Control_Panel Pin Buttons"
    update_interval: 1s
    unit_of_measurement: code
    id: panel_adc_sensor
    filters:
      - lambda: |-
          return ( x * (1023 / 3.3));
#      - lambda: |-
#          return (x * 100000000);
      - lambda: |-
          if (x > 100) {
            return x;
          } else {
            return 0.0;
          }
      # - filter_out: 0.0
      # - filter_out: 585.93758
      # - filter_out: 488.28125

binary_sensor:
    - platform: status
      name: "MintyMCU_Control_Panel Status"
    - platform: template
      name: "MintyMCU_Control_Panel Volume Mute Trigger Sensor"
      id: sensor_trigger_speakers_mute
    - platform: template
      name: "MintyMCU_Control_Panel Power Trigger Sensor"
      id: sensor_trigger_speakers_power
    - platform: template
      name: "MintyMCU_Control_Panel Button K7"
      id: sensor_panel_button_k7
      lambda: |-
        if (id(panel_adc_sensor).state >= 230.0 && id(panel_adc_sensor).state <= 231) {
          // Button pressed.
          return true;
        } else {
          // Button not pressed.
          return false;
        }

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "MintyMCU_Control_Panel IP Address"
    ssid:
      name: "MintyMCU_Control_Panel Connected SSID"
    bssid:
      name: "MintyMCU_Control_Panel Connected BSSID"
  - platform: version
    name: "MintyMCU_Control_Panel ESPHome Version"

# secret: !include secrets.yaml
